modLoader="javafml"
loaderVersion="[38,)"
license="All rights reserved"
issueTrackerURL="https://github.com/TwelveIterationMods/CraftingTweaks/issues"

[[mods]]
modId="craftingtweaks"
version="${file.jarVersion}"
displayName="CraftingTweaks"
displayURL="https://blay09.net/mods/craftingtweaks"
logoFile="craftingtweaks-icon.png"
credits="BlayTheNinth"
authors="BlayTheNinth"
description='''
Allows you to rotate, balance or clear the crafting matrix by the press of a button, in any (supported) crafting window.
'''

[[dependencies.craftingtweaks]]
    modId="forge"
    mandatory=true
    versionRange="[38,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.craftingtweaks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.craftingtweaks]]
    modId="balm"
    mandatory=true
    versionRange="[3.1.0,)"
    ordering="NONE"
    side="BOTH"